#ifndef GRAPHICS_ERROR_H
#define GRAPHICS_ERROR_H

#include <vulkan/vulkan.h>

typedef enum GraphicsError {
    GRAPHICS_OK = 0,
    GRAPHICS_ERR_INVALID_ARGUMENT,
    GRAPHICS_ERR_OUT_OF_MEMORY,

    GRAPHICS_ERR_WINDOW_SYSTEM_INIT_FAILED,
    GRAPHICS_ERR_EXTENSION_FETCH_FAILED,
    GRAPHICS_ERR_EXTENSION_UNSUPPORTED,
    GRAPHICS_ERR_PHYSICAL_DEVICE_FETCH_FAILED,
    GRAPHICS_ERR_PHYSICAL_DEVICE_PICK_FAILED,
    GRAPHICS_ERR_INSTANCE_CREATION_FAILED,
    GRAPHICS_ERR_DEBUG_MESSENGER_CREATION_FAILED,
    GRAPHICS_ERR_LOGICAL_DEVICE_CREATION_FAILED,
    GRAPHICS_ERR_VMA_ALLOCATOR_CREATION_FAILED,
    GRAPHICS_ERR_COMMAND_POOL_CREATION_FAILED,

    GRAPHICS_ERR_NO_CONTEXT_INIT,
    GRAPHICS_ERR_WINDOW_CREATE_FAILED,
    GRAPHICS_ERR_SURFACE_CREATION_FAILED,
    GRAPHICS_ERR_VULKAN_INIT_FAILED,

    GRAPHICS_ERR_SWAPCHAIN_CREATION_FAILED,
    GRAPHICS_ERR_SWAPCHAIN_IMAGE_VIEWS_CREATION_FAILED,

    GRAPHICS_ERR_DEPTH_IMAGE_CREATION_FAILED,
    GRAPHICS_ERR_DEPTH_IMAGE_VIEW_CREATION_FAILED,

    GRAPHICS_ERR_COLOR_IMAGE_CREATION_FAILED,
    GRAPHICS_ERR_COLOR_IMAGE_VIEW_CREATION_FAILED,

    GRAPHICS_ERR_RESOLVE_IMAGE_CREATION_FAILED,
    GRAPHICS_ERR_RESOLVE_IMAGE_VIEW_CREATION_FAILED,

    GRAPHICS_ERR_SEMAPHORE_CREATION_FAILED,
    GRAPHICS_ERR_FENCE_CREATION_FAILED,

    GRAPHICS_ERR_COMMAND_BUFFER_ALLOCATION_FAILED,

    GRAPHICS_ERR_PIPELINE_CACHE_CREATION_FAILED,
    GRAPHICS_ERR_PIPELINE_CREATION_FAILED,
    GRAPHICS_ERR_PIPELINE_LAYOUT_CREATION_FAILED,

    GRAPHICS_ERR_DESCRIPTOR_SET_LAYOUT_CREATION_FAILED,
    GRAPHICS_ERR_DESCRIPTOR_POOL_CREATION_FAILED,
    GRAPHICS_ERR_DESCRIPTOR_SET_ALLOCATION_FAILED,
    GRAPHICS_ERR_SAMPLER_CREATION_FAILED,

    GRAPHICS_ERR_IMAGE_CREATION_FAILED,
    GRAPHICS_ERR_IMAGE_VIEW_CREATION_FAILED,

    GRAPHICS_ERR_IO,
    GRAPHICS_ERR_SHADER_MODULE_CREATION_FAILED
} GraphicsError;

typedef struct GraphicsResult {
    GraphicsError err;
    VkResult       vk;
} GraphicsResult;

const char *graphics_err_str(GraphicsError err);
const char *vk_result_str(VkResult result);

#endif
